# Generated by Django 5.2.5 on 2025-08-27 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factchecks', '0006_factcheck_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_extracted', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('suggested_verdict', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('misleading', 'Misleading'), ('unverifiable', 'Unverifiable')], default='unverifiable', max_length=20)),
                ('evidence_sources', models.JSONField(default=list)),
                ('similar_claims', models.JSONField(default=list)),
                ('processing_time', models.FloatField(default=0.0)),
                ('ai_model_used', models.CharField(default='gpt-4', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='factchecks.submission')),
            ],
            options={
                'verbose_name_plural': 'AI Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
