# Generated by Django 5.2.5 on 2025-08-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url_submitted', models.URLField(blank=True, max_length=500)),
                ('verdict', models.CharField(choices=[('True', 'True'), ('Mostly True', 'Mostly True'), ('Mixture', 'Mixture'), ('Mostly False', 'Mostly False'), ('False', 'False'), ('Unverifiable', 'Unverifiable')], max_length=20)),
                ('summary', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
