# Generated by Django 5.2.5 on 2025-08-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_name', models.CharField(blank=True, max_length=100)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('claim_text', models.TextField(blank=True)),
                ('url_submitted', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('completed', 'Fact-Check Completed')], default='new', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
