# Generated by Django 5.2.5 on 2025-08-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecks', '0002_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositiveContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('culture', 'Culture & Arts'), ('innovation', 'Innovation & Technology'), ('community', 'Community Initiatives'), ('nature', 'Nature & Tourism'), ('achievement', 'Achievements & Success')], max_length=20)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
