# Generated by Django 5.2.5 on 2025-08-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecks', '0003_positivecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='positivecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='positive_content/'),
        ),
    ]
