# Generated by Django 5.2.5 on 2025-08-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecks', '0004_positivecontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='user_notified',
            field=models.BooleanField(default=False),
        ),
    ]
