# Generated by Django 5.2.5 on 2025-08-24 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecks', '0005_submission_date_notified_submission_user_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='factcheck',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_checks', to='factchecks.submission'),
        ),
    ]
