# Generated by Django 5.2.5 on 2025-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factchecks', '0006_factcheck_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
